[project]
name = "brave-it"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django==5.2",
    "gunicorn==23.0.0",
    "oracledb==3.1.0",
    "pillow>=11.3.0",
]
