# Generated by Django 5.2 on 2025-09-08 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"managed": False},
        ),
    ]
